### ISSUE TITLE
10连出错

### ISSUE THREAD

**Issue by Darknights-master** [Darknights-dev/Darknights-server#1]
tenAdvanceGacha中出现重复干员会引发客户端错误

**Comment by Darknights-master** [comment]
Do you have some suggestions? @guch8017 
It seems [ArknightsGachaMonitor](https://github.com/guch8017/ArknightsGachaMonitor) works well.

**Comment by Rhine-Department-0xf** [comment]
Maybe because of instId

**Comment by WinHGGG** [comment]
> Maybe because of instId

I reused his code, and now it seems good.

**Comment by Darknights-master** [comment]
fixed.
